name: Sync strings.json to translations on PR Update

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths:
      - 'custom_components/lynkco/strings.json'

jobs:
  sync-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.HASSLYNKCORELEASEBOTID }}
          private-key: ${{ secrets.HASSLYNKCORELEASEBOTPRIVATEKEY }}

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Sync strings.json to en.json
        run: |
          cp custom_components/lynkco/strings.json custom_components/lynkco/translations/en.json

      - name: Commit changes
        run: |
          git add custom_components/lynkco/translations/en.json
          git commit -m "Automatically sync strings.json to en.json" || echo "No changes to commit."
          git push origin HEAD:${{ github.head_ref }}
